@baseurl = http://localhost:5000

###
GET {{baseurl}}/api/form-layout/example

###
GET {{baseurl}}/api/form-default-data/example

###
GET {{baseurl}}/api/list-items/example/cidades?query=a
content-type: application/json


###
POST {{baseurl}}/api/render-doc/example
content-type: application/json
X-CSRFToken: token_csrf

{
    "nome": "João Pereira", 
    "date": "12/12/2021",
    "float_value": "12,3", 
    "pessoas": 
    [
        {"nome": "Gape Gomes", "profissao": "Perito Criminal"},
        {"nome": "Gape Steven", "profissao": "Auxiliar de Autopsia"}
    ], 
    "texto_long": "Texte de texto longo no widget TextAreaWidget", 
    "test_typeahead": {"key": "Goiânia", "value": "Goiânia"}
}

###
GET {{baseurl}}/api/widget-asset/12456asdf/fotos/teste/teste2
content-type: application/json